name: front_end
description: Taxon Hub

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vrouter: ^1.2.1
  csv: ^5.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  file_picker: ^4.6.1
  dio: ^4.0.6
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
