version: '3.7'


services: 
  taxonhub_db:
    image: postgres
    container_name: taxonhub_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=txhub
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=taxonhub
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: taxonhub
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - taxonhub_db
    depends_on:
      - taxonhub_db
volumes:
  pgdata:
    driver: local
  
